spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        livenessProbe:
          httpGet:
              path: /authserver/health
              port: 9090
              scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
              path: /authserver/health
              port: 9090
              scheme: HTTP
          initialDelaySeconds: 30