CREATE TABLE SSO_TOKEN 
   (    
    TOKEN VARCHAR NOT NULL, 
    REFERENCE_DATA VARCHAR, 
    PERM_ID INT, 
    USERNAME VARCHAR, 
    CREATION_DATE VARCHAR NOT NULL, 
    RETURN_URL VARCHAR, 
    AUTHORIZED INT NOT NULL
   ); 