apiVersion: v1
kind: Secret
metadata:
  name: config-server-cryptography-secrets
type: Opaque
data: 
  location: ZmlsZTovLy9jcnlwdG9ncmFwaHkva2V5c3RvcmUvY29uZmlnU2VydmVyLmprcw==
  alias: Y29uZmlnU2VydktleQ==
  password: bGV0bWVpbg==
  secret: RGV2Q29uZmlnU2VydlBhc3M=