server:
  port: 8085
  context-path: /customer
spring:
  application:
    name: customer_server
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console 
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/authserver/me
      id: customer
      prefer-token-info: true
logging:
    level:
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
