CREATE TABLE "CUSTOMER_PROFILE" 
   (    "PROFILE_ID" VARCHAR NOT NULL, 
    "PERM_ID" INT, 
    "USERNAME" VARCHAR NOT NULL, 
    "PASSWORD_HASH" VARCHAR NOT NULL, 
    "PASSWORD_SALT" DECIMAL NOT NULL, 
    "EMAIL" VARCHAR NOT NULL, 
    "DATE_OF_BIRTH" VARCHAR, 
    "STATUS" VARCHAR NOT NULL,
    "USER_INTERFACE" VARCHAR, 
    "GENDER" VARCHAR);
    