spring:
  datasource:
    url: jdbc:mysql://50.116.69.13:3306/vendolat_oauth2?useSSL=false
    username: vendolat_oauth2
    password: User123
server:
  port: 9090
  ssl:
        key-store: classpath:keystore.jks
        key-store-password: password
        key-password: password
  context-path: /authserver
security:
    user:
        password: password
logging:
    level:
        org.springframework.security: DEBUG