spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        env:
          - name: CONFIG_SERVER_USER
            valueFrom:
              secretKeyRef: 
                key: username
                name: config-server-secrets
          - name: CONFIG_SERVER_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: password
                name: config-server-secrets
          - name: KEY_STORE_LOCATION
            valueFrom:
              secretKeyRef: 
                key: location
                name: config-server-cryptography-secrets
          - name: KEY_STORE_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: password
                name: config-server-cryptography-secrets
          - name: KEY_STORE_ALIAS
            valueFrom:
              secretKeyRef: 
                key: alias
                name: config-server-cryptography-secrets
          - name: KEY_STORE_SECRET
            valueFrom:
              secretKeyRef: 
                key: secret
                name: config-server-cryptography-secrets
          - name: GIT_DEFAULT_REPO_URI
            valueFrom:
              secretKeyRef: 
                key: uri
                name: git-default-repo-secrets
          - name: GIT_DEFAULT_REPO_USERNAME
            valueFrom:
              secretKeyRef: 
                key: uri
                name: git-default-repo-secrets
          - name: GIT_DEFAULT_REPO_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: password
                name: git-default-repo-secrets
          - name: NEW_RELIC_LICENSE
            valueFrom:
              secretKeyRef: 
                key: license
                name: newrelic-license-key-secrets
          - name: PROFILE_ACTIVE
            valueFrom:
              configMapKeyRef: 
                key: profile
                name: profile-active-configmap
        volumeMounts: 
        - mountPath: /keystore
          name: java-keystore
          readOnly: true
        livenessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 30
      volumes: 
      - name: java-keystore
        secret: 
          secretName: config-server-keystore