spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        env:
          - name: CONFIG_SERVER_USER
            valueFrom:
              secretKeyRef: 
                key: username
                name: config-server-secrets
          - name: CONFIG_SERVER_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: password
                name: config-server-secrets
          - name: KEY_STORE_LOCATION
            valueFrom:
              secretKeyRef: 
                key: location
                name: config-server-cryptography-secrets
          - name: KEY_STORE_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: password
                name: config-server-cryptography-secrets
          - name: KEY_STORE_ALIAS
            valueFrom:
              secretKeyRef: 
                key: alias
                name: config-server-cryptography-secrets
          - name: KEY_STORE_SECRET
            valueFrom:
              secretKeyRef: 
                key: secret
                name: config-server-cryptography-secrets
          - name: GIT_DEFAULT_REPO_URI
            valueFrom:
              secretKeyRef: 
                key: default-uri
                name: git-configserver-repo-secrets
          - name: GIT_DEFAULT_REPO_USERNAME
            valueFrom:
              secretKeyRef: 
                key: defaultrepo-username
                name: git-configserver-repo-secrets
          - name: GIT_DEFAULT_REPO_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: defaultrepo-password
                name: git-configserver-repo-secrets
          - name: GIT_AUTHSERVER_REPO_URI
            valueFrom:
              secretKeyRef:
                key: authorization-server-uri
                name: git-configserver-repo-secrets
          - name: GIT_AUTHSERVER_REPO_USERNAME
            valueFrom:
              secretKeyRef:
                key: authorization-server-username
                name: git-configserver-repo-secrets
          - name: GIT_AUTHSERVER_REPO_PASSWORD
            valueFrom:
              secretKeyRef:
                key: authorization-server-password
                name: git-configserver-repo-secrets
          - name: NEW_RELIC_LICENSE
            valueFrom:
              secretKeyRef: 
                key: license
                name: newrelic-license-key-secrets
          - name: PROFILE_ACTIVE
            valueFrom:
              configMapKeyRef: 
                key: profile
                name: profile-active-configmap
          - name: LOGBACK_AMQP_HOST
            valueFrom:
              secretKeyRef: 
                key: rabbit-host
                name: logback-amqp-secrets
          - name: LOGBACK_AMQP_PORT
            valueFrom:
              secretKeyRef: 
                key: rabbit-port
                name: logback-amqp-secrets
          - name: LOGBACK_AMQP_USER
            valueFrom:
              secretKeyRef: 
                key: rabbit-user
                name: logback-amqp-secrets
          - name: LOGBACK_AMQP_PASSWORD
            valueFrom:
              secretKeyRef: 
                key: rabbit-password
                name: logback-amqp-secrets
          - name: LOGBACK_AMQP_EXCHANGE_NAME
            valueFrom:
              configMapKeyRef: 
                key: exchange-name
                name: logback-amqp-configmaps
          - name: LOGBACK_AMQP_EXCHANGE_TYPE
            valueFrom:
              configMapKeyRef: 
                key: exchange-type
                name: logback-amqp-configmaps
          - name: LOGBACK_AMQP_DELIVERY_MODE
            valueFrom:
              configMapKeyRef: 
                key: delivery-mode
                name: logback-amqp-configmaps
          - name: LOGBACK_AMQP_SENDER_POOL_SIZE
            valueFrom:
              configMapKeyRef: 
                key: senderpool-size
                name: logback-amqp-configmaps
          - name: LOGBACK_AMQP_MAX_SENDER_RETRIES
            valueFrom:
              configMapKeyRef: 
                key: maxsender-retries
                name: logback-amqp-configmaps
          - name: LOGBACK_ROUTING_KEY_PATTERN
            valueFrom:
              configMapKeyRef: 
                key: routingkey-pattern
                name: logback-amqp-configmaps
          - name: LOGBACK_DECLARE_EXCHANGE
            valueFrom:
              configMapKeyRef: 
                key: declare-exchange
                name: logback-amqp-configmaps
        volumeMounts: 
        - mountPath: /keystore
          name: java-keystore
          readOnly: true
        resources:
          limits:
            memory: 700Mi
        livenessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 30
      volumes: 
      - name: java-keystore
        secret: 
          secretName: config-server-keystore