spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        livenessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
              path: /health
              port: 8888
              scheme: HTTP
          initialDelaySeconds: 30